---
title: "Metabolomics Baseline Analysis"
subtitle: "Association analysis via regression"
author: "Sofie Olund Villumsen"
date: "17/9/2021"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

Associate selected clinical variable with the top metabolites found in previous analysis

# Initial settings
```{r echo=FALSE}
# Clear workspace
rm(list = ls()) 
```

Load packages
```{r message=FALSE}
library(tidyverse)
```


Load data
```{r message=FALSE}
path <- "L:/LovbeskyttetMapper/HCOF Stem Cells/Sofie/Baseline_study/Metabolomics/"
setwd(path)

combined_data <- read_csv(paste(path, "data/02_combined_data_imputed_log2_zscore.csv", sep="/")) %>% 
  filter(Label == "A") %>% 
  mutate(bwcat_NAFLD_bin = case_when(bwcat_NAFLD == "NBW_FALSE" ~ 0,
                                     bwcat_NAFLD == "LBW_FALSE" ~ 1,
                                     bwcat_NAFLD == "LBW_TRUE" ~ 2), 
         bwcat_bin = case_when(bwcat == "NBW" ~ 0,
                               bwcat == "LBW" ~ 1)) %>% 
  
  select(Sample_ID, bwcat, randomization, NAFLD, Label, bwcat_NAFLD_bin, bwcat_NAFLD, everything())
```



```{r}
# Convert data frame from numeric to factor
indx <- sapply(combined_data, is.numeric)
combined_data[indx] <- lapply(combined_data[indx], function(combined_data) as.factor(as.character(combined_data)))
combined_data <- combined_data[7:137]

# Set random seed 
if(exists(".Random.seed")) rm(.Random.seed)

library(impute) # Imputing data with KNN
# Impute with KNN function
combined_data_imputed <- impute.knn(as.matrix(combined_data))
```



```{r}
library(readxl)

lm_bwcatNAFLD = lm(bwcat_bin~Leucine+Hippuric.acid+c.peptide+height_day1+liverfatpercent, data = combined_data) 

summary(lm_bwcatNAFLD)
```

```{r}
mylogit = glm(formula = bwcat_NAFLD_bin~Leucine+Hippuric.acid+c.peptide+height_day1+liverfatpercent,data = combined_data)
summary(mylogit)
```


